import { ConferenceStatus } from "@prisma/client";
import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

export async function seedConferences() {
  const conferences = [
    {
      title: "Indonesia AI Summit 2026",
      description:
        "Konferensi nasional mengenai penerapan Artificial Intelligence di berbagai sektor industri.",
      city: "Jakarta",
      venue: "Jakarta Convention Center",
      startDate: new Date("2026-09-10T09:00:00"),
      endDate: new Date("2026-09-10T17:00:00"),
      isFree: false,
      status: ConferenceStatus.PUBLISHED,
      organizerId: 1,
      categoryId: 1,
    },
    {
      title: "Cloud Indonesia Expo",
      description:
        "Membahas implementasi cloud computing untuk perusahaan modern.",
      city: "Jakarta",
      venue: "Balai Kartini",
      startDate: new Date("2026-10-08T09:00:00"),
      endDate: new Date("2026-10-08T17:00:00"),
      isFree: false,
      status: ConferenceStatus.PUBLISHED,
      organizerId: 2,
      categoryId: 5,
    },
    {
      title: "Indonesia DevOps Conference",
      description:
        "Best practice DevOps, CI/CD, automation, dan observability.",
      city: "Jakarta",
      venue: "The Kasablanka Hall",
      startDate: new Date("2026-11-15T09:00:00"),
      endDate: new Date("2026-11-15T17:00:00"),
      isFree: false,
      status: ConferenceStatus.PUBLISHED,
      organizerId: 3,
      categoryId: 9,
    },

    {
      title: "Bandung Software Engineering Conference",
      description:
        "Software architecture, clean code, testing, dan scalable systems.",
      city: "Bandung",
      venue: "Sasana Budaya Ganesha",
      startDate: new Date("2026-09-18T09:00:00"),
      endDate: new Date("2026-09-18T17:00:00"),
      isFree: false,
      status: ConferenceStatus.PUBLISHED,
      organizerId: 2,
      categoryId: 2,
    },
    {
      title: "Bandung Web Tech Summit",
      description: "Frontend, backend, dan full-stack web development terbaru.",
      city: "Bandung",
      venue: "Trans Convention Centre",
      startDate: new Date("2026-10-20T09:00:00"),
      endDate: new Date("2026-10-20T17:00:00"),
      isFree: true,
      status: ConferenceStatus.PUBLISHED,
      organizerId: 1,
      categoryId: 8,
    },
    {
      title: "Bandung Machine Learning Forum",
      description: "Implementasi machine learning untuk bisnis dan riset.",
      city: "Bandung",
      venue: "Telkom University Convention Hall",
      startDate: new Date("2026-11-05T09:00:00"),
      endDate: new Date("2026-11-05T17:00:00"),
      isFree: false,
      status: ConferenceStatus.PUBLISHED,
      organizerId: 3,
      categoryId: 6,
    },

    {
      title: "Surabaya Cyber Security Forum",
      description:
        "Keamanan siber, penetration testing, dan incident response.",
      city: "Surabaya",
      venue: "Grand City Convention Hall",
      startDate: new Date("2026-09-24T09:00:00"),
      endDate: new Date("2026-09-24T17:00:00"),
      isFree: false,
      status: ConferenceStatus.PUBLISHED,
      organizerId: 3,
      categoryId: 3,
    },
    {
      title: "Surabaya Cloud Native Day",
      description: "Kubernetes, Docker, microservices, dan cloud native.",
      city: "Surabaya",
      venue: "Dyandra Convention Center",
      startDate: new Date("2026-10-27T09:00:00"),
      endDate: new Date("2026-10-27T17:00:00"),
      isFree: true,
      status: ConferenceStatus.PUBLISHED,
      organizerId: 2,
      categoryId: 5,
    },
    {
      title: "East Java Mobile Developer Summit",
      description: "Android, iOS, Flutter, dan React Native.",
      city: "Surabaya",
      venue: "Hotel Majapahit",
      startDate: new Date("2026-11-18T09:00:00"),
      endDate: new Date("2026-11-18T17:00:00"),
      isFree: false,
      status: ConferenceStatus.PUBLISHED,
      organizerId: 1,
      categoryId: 7,
    },

    {
      title: "Padang Digital Innovation Summit",
      description:
        "Forum transformasi digital dan inovasi teknologi di Sumatera Barat.",
      city: "Padang",
      venue: "Mercure Padang",
      startDate: new Date("2026-10-03T09:00:00"),
      endDate: new Date("2026-10-03T17:00:00"),
      isFree: true,
      status: ConferenceStatus.PUBLISHED,
      organizerId: 1,
      categoryId: 4,
    },
    {
      title: "West Sumatra AI Conference",
      description:
        "Pemanfaatan AI untuk sektor pendidikan, kesehatan, dan UMKM.",
      city: "Padang",
      venue: "Universitas Andalas Convention Hall",
      startDate: new Date("2026-11-07T09:00:00"),
      endDate: new Date("2026-11-07T17:00:00"),
      isFree: false,
      status: ConferenceStatus.PUBLISHED,
      organizerId: 2,
      categoryId: 1,
    },
    {
      title: "Sumatra Cyber Security Forum",
      description: "Keamanan digital untuk organisasi dan pemerintahan.",
      city: "Padang",
      venue: "Truntum Padang Hotel",
      startDate: new Date("2026-12-03T09:00:00"),
      endDate: new Date("2026-12-03T17:00:00"),
      isFree: false,
      status: ConferenceStatus.PUBLISHED,
      organizerId: 3,
      categoryId: 3,
    },

    {
      title: "Yogyakarta Data Science Summit",
      description: "Data analytics, visualization, dan business intelligence.",
      city: "Yogyakarta",
      venue: "Jogja Expo Center",
      startDate: new Date("2026-10-10T09:00:00"),
      endDate: new Date("2026-10-10T17:00:00"),
      isFree: false,
      status: ConferenceStatus.PUBLISHED,
      organizerId: 2,
      categoryId: 4,
    },
    {
      title: "Jogja Developer Meetup",
      description:
        "Komunitas developer berbagi pengalaman dan teknologi terbaru.",
      city: "Yogyakarta",
      venue: "Universitas Gadjah Mada",
      startDate: new Date("2026-11-14T09:00:00"),
      endDate: new Date("2026-11-14T17:00:00"),
      isFree: true,
      status: ConferenceStatus.PUBLISHED,
      organizerId: 1,
      categoryId: 8,
    },
    {
      title: "Yogyakarta Blockchain Forum",
      description: "Blockchain, Web3, smart contract, dan aset digital.",
      city: "Yogyakarta",
      venue: "Royal Ambarrukmo",
      startDate: new Date("2026-12-08T09:00:00"),
      endDate: new Date("2026-12-08T17:00:00"),
      isFree: false,
      status: ConferenceStatus.PUBLISHED,
      organizerId: 3,
      categoryId: 10,
    },
    {
      title: "Semarang Tech Innovation Summit",
      description:
        "Konferensi mengenai inovasi teknologi untuk sektor bisnis dan pemerintahan.",
      city: "Semarang",
      venue: "MG Setos Hotel",
      startDate: new Date("2026-09-22T09:00:00"),
      endDate: new Date("2026-09-22T17:00:00"),
      isFree: true,
      status: ConferenceStatus.PUBLISHED,
      organizerId: 1,
      categoryId: 2,
    },
    {
      title: "Java Cloud Summit",
      description:
        "Cloud infrastructure, serverless architecture, dan enterprise cloud.",
      city: "Semarang",
      venue: "Gumaya Tower Hotel",
      startDate: new Date("2026-10-25T09:00:00"),
      endDate: new Date("2026-10-25T17:00:00"),
      isFree: false,
      status: ConferenceStatus.PUBLISHED,
      organizerId: 2,
      categoryId: 5,
    },
    {
      title: "Semarang DevOps Meetup",
      description: "Automation, CI/CD, observability, dan Kubernetes.",
      city: "Semarang",
      venue: "PO Hotel Semarang",
      startDate: new Date("2026-11-28T09:00:00"),
      endDate: new Date("2026-11-28T17:00:00"),
      isFree: true,
      status: ConferenceStatus.PUBLISHED,
      organizerId: 3,
      categoryId: 9,
    },

    {
      title: "North Sumatra AI Forum",
      description: "Artificial Intelligence untuk industri dan layanan publik.",
      city: "Medan",
      venue: "Santika Premiere Dyandra Hotel",
      startDate: new Date("2026-09-30T09:00:00"),
      endDate: new Date("2026-09-30T17:00:00"),
      isFree: false,
      status: ConferenceStatus.PUBLISHED,
      organizerId: 2,
      categoryId: 1,
    },
    {
      title: "Medan Software Engineering Day",
      description: "Software engineering modern untuk enterprise application.",
      city: "Medan",
      venue: "JW Marriott Medan",
      startDate: new Date("2026-11-12T09:00:00"),
      endDate: new Date("2026-11-12T17:00:00"),
      isFree: false,
      status: ConferenceStatus.PUBLISHED,
      organizerId: 1,
      categoryId: 2,
    },
    {
      title: "Sumatra Data Analytics Summit",
      description: "Data warehouse, business intelligence, dan analytics.",
      city: "Medan",
      venue: "Grand City Hall Medan",
      startDate: new Date("2026-12-10T09:00:00"),
      endDate: new Date("2026-12-10T17:00:00"),
      isFree: true,
      status: ConferenceStatus.PUBLISHED,
      organizerId: 3,
      categoryId: 4,
    },

    {
      title: "Eastern Indonesia Tech Conference",
      description: "Konferensi teknologi terbesar di kawasan Indonesia Timur.",
      city: "Makassar",
      venue: "Claro Hotel Makassar",
      startDate: new Date("2026-10-07T09:00:00"),
      endDate: new Date("2026-10-07T17:00:00"),
      isFree: false,
      status: ConferenceStatus.PUBLISHED,
      organizerId: 3,
      categoryId: 8,
    },
    {
      title: "Makassar Cyber Defense Summit",
      description: "Cyber security awareness dan penetration testing.",
      city: "Makassar",
      venue: "Four Points by Sheraton",
      startDate: new Date("2026-11-20T09:00:00"),
      endDate: new Date("2026-11-20T17:00:00"),
      isFree: false,
      status: ConferenceStatus.PUBLISHED,
      organizerId: 2,
      categoryId: 3,
    },
    {
      title: "Sulawesi Mobile Developer Conference",
      description: "Cross-platform mobile development dan best practice.",
      city: "Makassar",
      venue: "Unhas Hotel & Convention",
      startDate: new Date("2026-12-15T09:00:00"),
      endDate: new Date("2026-12-15T17:00:00"),
      isFree: true,
      status: ConferenceStatus.PUBLISHED,
      organizerId: 1,
      categoryId: 7,
    },

    {
      title: "Bali DevFest",
      description: "Festival teknologi untuk developer dan startup Indonesia.",
      city: "Denpasar",
      venue: "Bali Nusa Dua Convention Center",
      startDate: new Date("2026-10-15T09:00:00"),
      endDate: new Date("2026-10-15T17:00:00"),
      isFree: false,
      status: ConferenceStatus.PUBLISHED,
      organizerId: 1,
      categoryId: 8,
    },
    {
      title: "Bali Machine Learning Summit",
      description: "Machine learning untuk bisnis, kesehatan, dan pariwisata.",
      city: "Denpasar",
      venue: "The Westin Resort Nusa Dua",
      startDate: new Date("2026-11-22T09:00:00"),
      endDate: new Date("2026-11-22T17:00:00"),
      isFree: false,
      status: ConferenceStatus.PUBLISHED,
      organizerId: 3,
      categoryId: 6,
    },
    {
      title: "Bali Blockchain Conference",
      description: "Blockchain, Web3, tokenization, dan smart contract.",
      city: "Denpasar",
      venue: "Discovery Kartika Plaza Hotel",
      startDate: new Date("2026-12-18T09:00:00"),
      endDate: new Date("2026-12-18T17:00:00"),
      isFree: true,
      status: ConferenceStatus.PUBLISHED,
      organizerId: 2,
      categoryId: 10,
    },

    {
      title: "Batam Digital Economy Summit",
      description: "Digital economy, fintech, dan transformasi industri.",
      city: "Batam",
      venue: "Radisson Golf & Convention Center",
      startDate: new Date("2026-10-28T09:00:00"),
      endDate: new Date("2026-10-28T17:00:00"),
      isFree: false,
      status: ConferenceStatus.PUBLISHED,
      organizerId: 2,
      categoryId: 4,
    },
    {
      title: "Batam Cloud Infrastructure Day",
      description: "Cloud infrastructure dan modern data center.",
      city: "Batam",
      venue: "Harris Hotel Batam Center",
      startDate: new Date("2026-12-05T09:00:00"),
      endDate: new Date("2026-12-05T17:00:00"),
      isFree: false,
      status: ConferenceStatus.PUBLISHED,
      organizerId: 1,
      categoryId: 5,
    },
    {
      title: "Batam Software Developer Meetup",
      description: "Sharing session developer Indonesia dan Singapura.",
      city: "Batam",
      venue: "Pacific Palace Hotel",
      startDate: new Date("2026-12-22T09:00:00"),
      endDate: new Date("2026-12-22T17:00:00"),
      isFree: true,
      status: ConferenceStatus.PUBLISHED,
      organizerId: 3,
      categoryId: 2,
    },
  ];
  await prisma.conference.createMany({
    data: conferences,
    skipDuplicates: true,
  });

  console.log("✅ Conferences seeded.");
}